# docker compose up -d
# docker compose up --pull never
# docker compose down


version: "3.8"

services:
  db:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
      TZ: Europe/Berlin
    volumes:
      - ./postgres:/var/lib/postgresql/data